#!/bin/bash
#  Bash script for easy control and access to Samba resources
#  https://github.com/martin-rizzo/ZZScripts
#  by Martin Rizzo
ScriptName="${0##*/}";ScriptVersion=0.1
Help="
Usage: $ScriptName COMMAND [resource]

Admin Commands:
    $ScriptName info  [host]
    $ScriptName fstab [host]
    $ScriptName secure

User Commands:
    $ScriptName list
    $ScriptName mount  <dir>
    $ScriptName umount <dir>

Options:
    -h, --help     display this help
    -V, --version  display script version

Examples:
    ....
"

# CONSTANTS (can be modified by the arguments passed to the script)
SambaUser=
SambaHost=
Disk=


#---------------------------------- HELPERS ---------------------------------#

function set_disk() {
    if [[ "$1" =~ ^[0-9]+$ || "$1" == /* ]]; then
      Disk="$1"
    else
      Disk="/$1"
    fi
}

## Verifies if a disk was selected by the user
##
## @param selection      the user selection (an order number or disk name)
## @param disk_idx       the disk index in the list
## @param disk_smbname   the disk's samba resource name
## @param disk_mount     the path where the disk is mounted
##
function is_selected_disk() {
    local selection=$1
    local disk_idx=$2 disk_smbname=$3 disk_mount=$4

    if [[ ! $selection ]]; then
        return 0
    elif [[ $selection = $disk_idx ]]; then
        return 0
    else
        case "${disk_mount,,}" in
          *"${selection,,}")
            return 0
            ;;
        esac
    fi
    return 1
}

function parse_samba_path() {
    local path=$1
    SambaUser=${path%@*}
    [[ "$SambaUser" == "$path" ]] && SambaUser=$USER
    Disk=${path#*/}
    [[ "$Disk" == "$path" ]] && Disk=""
    SambaHost=${path#$SambaUser@}
    SambaHost=${SambaHost%/$Disk}
}


function proc_samba_disks() {
    local smbuser="$1" smbhost="$2" funct="$3"
    local disklines name type comment

    echo    "Logging in to $smbuser@$smbhost"
    echo -n 'Password: '
    disklines=$(smbclient -L $smbhost -U $smbuser | grep -i 'Disk')
    echo

    $funct '#BEGIN'
    while read diskline; do
      diskline=$(echo $diskline)
      name="${diskline%% *}"; diskline="${diskline#* }"
      type="${diskline%% *}"; diskline="${diskline#* }"
      comment="$diskline"
      $funct '#ITEM' "$name" "$type" "$comment"
      if [[ $? != 0 ]]; then
        echo STOP!
        break
      fi
    done <<< "$disklines"
    $funct '#END'
}

## Reads the file /etc/fstab line by line and calls the function specified
## as argument to process each samba disk that is detected (and meets the
## filters)
##
## The global var 'found' will be set if any disk was found.
##
## @param function_name
##     The function to call to process each samba disk.
##     It should accept the following parameters:
##         $1: The samba disk index (starting at 1)
##         $1: The device name, eg.: //sambaserver/Disk
##         $2: The mount point, eg.: /home/user/ServerName/Disk
##         $3: The file system type, eg.: cifs
##         $4: The mount options separated by commas.
##
## @param user
##     (used as filter) The user
##
## @param selection
##     (used as filter) The order number or name of the disk
##
function foreach_disk() {
    local function_name="$1" user="$2" selection="$3"
    local index=1 fields disk_name mount_pt fs_type options
    found=''
    while IFS= read -r line; do
      if [[ $line != \#* ]]; then
        fields=($line)
        disk_name=${fields[0]}
        mount_pt=${fields[1]} ; fs_type=${fields[2]} ; options=${fields[3]}
        if [[ $fs_type != cifs ]]; then continue; fi
        if [[ $user ]] && [[ $options != *",uid=$user,"* ]]; then continue; fi

        if is_selected_disk "$selection" $index "$disk_name" "$mount_pt"; then
          found='YES'
          $function_name $index "$disk_name" "$mount_pt" "$fs_type" "$options" || break
        fi
        ((index++))
      fi
    done < "/etc/fstab"
}

#------------------------------- INFO COMMAND -------------------------------#

function print_disk_info() {
    local cmd="$1" name="$2" type="$3" comment="$4"
    [ "$cmd" = '#BEGIN' ] && echo -e "\n  [$SambaUser@$SambaHost]"
    [ "$cmd" = '#ITEM'  ] && printf '     +- %-14.14s %s\n' "$name" "$comment"
    [ "$cmd" = '#END'   ] && echo
}

function cmd_info() {
    parse_samba_path "$1"
    proc_samba_disks "$SambaUser" "$SambaHost" print_disk_info
}

#------------------------------ FSTAB COMMAND -------------------------------#

function print_fstab_conf() {
    local cmd="$1" diskname="$2" disktype="$3" comment="$4"
    local hostdir group flg1 flg2

    if [ "$cmd" = '#BEGIN' ]; then
      echo
      echo 'These lines must be added to /etc/fstab to allow mounting:'
      echo
    fi
    if [ "$cmd" = '#ITEM' ]; then
      hostdir='Mendoserver'
      group=$(id -g -n)
      resour="//$SambaHost/$diskname"
      mountdir="/home/$USER/$hostdir/$diskname"
      flg1="user,noauto,rw,uid=$USER,gid=$group,file_mode=0640,dir_mode=0750"
      flg2="credentials=/home/$USER/$hostdir/credentials"
      printf '%-30s %-40s cifs %-24s 0 0\n' "$resour" "$mountdir" "$flg1,$flg2"
    fi
    if [ "$cmd" = '#END' ]; then
      echo
    fi
}

function cmd_fstab() {
    parse_samba_path "$1"
    proc_samba_disks "$SambaUser" "$SambaHost" print_fstab_conf
}

#------------------------------ SECURE COMMAND ------------------------------#

function get_safety() {
    local path=$(which $1)
    local perbits=$(stat -c '%A' "$path")
    local status=${perbits:3:1}
    echo "$path" "$status" "$perbits"
}

function print_safety() {
    local path="$1" status="$2" perbits="$3"
    local comment suid
    case $status in
      x)
        suid='NO' ; comment='[user mounts not supported]'
        ;;
      s)
        suid='YES' ; comment=''
        ;;
      *)
        suid='ERR'
        ;;
    esac
    printf '    %-10s   %-4s  %-22s %s\n' "$perbits" "$suid" "$path" "$comment"
}

function cmd_safety() {
    local mount_path     mount_st
    local umount_path    umount_st
    local mountcifs_path mountcifs_st
    echo

    echo '  Enabling SUID on mount allows non-privileged users to mount file systems,'
    echo '  but disabling it improves security by limiting execution of this command.'
    echo

    echo '  Current state of the SUID bit:'
    read mount_path mount_st perbits <<< $(get_safety mount)
    print_safety "$mount_path" "$mount_st" "$perbits"
    read umount_path umount_st perbits <<< $(get_safety umount)
    print_safety "$umount_path" "$umount_st" "$perbits"
    read mountcifs_path mountcifs_st perbits <<< $(get_safety mount.cifs)
    print_safety "$mountcifs_path" "$mountcifs_st" "$perbits"
    echo


    if [ "$mount_st" != s -o "$umount_st" != s -o "$mountcifs_st" != s ]; then
    echo '  To allow users mount samba resources, try enabling SUID bit:'
    [ "$mount_st"     != s ] && echo "    > sudo chmod u+s $mount_path"
    [ "$umount_st"    != s ] && echo "    > sudo chmod u+s $umount_path"
    [ "$mountcifs_st" != s ] && echo "    > sudo chmod u+s $mountcifs_path"
    echo
    fi

    if [ "$mountcifs_st" == s ]; then
    echo '  If you just want to improve security then disable SUID bit:'
    echo '    ## this disable mount of samba resources for non-privileged users'
    echo "    > sudo chmod u-s $mountcifs_path"
    echo
    fi
}

#------------------------------- LIST COMMAND -------------------------------#

# These globals will be filled with the info of the disk with the longest name.
# They are used as examples of the 'zzsamba mount' subcommand.
EgNumber=
EgShortName=
EgLongName=

function print_disk() {
    local disk_idx="$1" path_array
    local disk_smbname="$2" disk_path="$3" disk_type="$4" disk_opts="$5"

    if [[ $disk_idx ]]; then
      IFS='/' read -ra path_array <<< "$disk_path"
      if [[ ${#EgShortName} -lt ${#path_array[-1]} ]]; then
        EgNumber=$disk_idx
        EgShortName=${path_array[-1]}
        EgLongName="${path_array[-2]}/${path_array[-1]}"
      fi
      printf '    %2d) %s\n' "$disk_idx" "${path_array[-2]}/${path_array[-1]}"
    else
      echo 'No disk found'
    fi
}

function cmd_list() {
    echo
    echo '  Available disks:'
    foreach_disk print_disk "$USER"
    if [[ $found ]]; then
      echo
      echo '  Disks can be mounted by its order number or its name:'
      echo "     > $ScriptName mount $EgNumber"
      echo "     > $ScriptName mount $EgShortName"
      echo "     > $ScriptName mount $EgLongName"
      echo
    else
      echo "    - no disk available for user $USER -"
      echo
    fi
}

#------------------------------- MOUNT COMMAND ------------------------------#

function mount_disk() {
    local disk_idx="$1"
    local disk_smbname="$2" disk_path="$3" disk_type="$4" disk_opts="$5"
    echo "Mounting $disk_path ..."
    mkdir -p "$disk_path"
    mount "$disk_path"
    return 1
}

function cmd_mount() {
    set_disk "$1"
    echo
    foreach_disk mount_disk "$USER" "$Disk"
    if [[ ! $found ]]; then
      echo "  - no disk named $Disk was found -"
    fi
    echo
}

#------------------------------- UMOUNT COMMAND -----------------------------#

function umount_disk() {
    local disk_idx="$1"
    local disk_smbname="$2" disk_path="$3" disk_type="$4" disk_opts="$5"
    echo "Unmounting $disk_path ..."
    umount "$disk_path"
    rmdir "$disk_path"
    return 1
}

function cmd_umount() {
    set_disk "$1"
    echo
    foreach_disk umount_disk "$USER" "$Disk"
    if [[ ! $found ]]; then
      echo "  - no disk named $Disk was found -"
    fi
    echo
}


#================================== START ==================================#

case "$1" in

  "info")
    cmd_info "$2"
    ;;
  "fstab")
    cmd_fstab "$2"
    ;;
  "secure")
    cmd_safety "$2"
    ;;
  "list")
    cmd_list "$2"
    ;;
  "mount")
    cmd_mount "$2"
    ;;
  "umount")
    cmd_umount "$2"
    ;;

esac

